config/routes.rb
Basic::Application.routes.draw do
	root :to => 'demo#index'
	get '/resources', to: 'demo#index'
	get 'pdfs', to: 'demo#pdfs'
	get 'images', to: 'demo#images'
	get 'new', to: 'demo#new'
	post '/new_upload', to: 'demo#new_upload'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController

before_action :check_configuration

  def check_configuration
    render 'configuration_missing' if Cloudinary.config.api_key.blank?
  end

	def index
		res = Cloudinary::Api.resources(resource: 'image', format: 'pdf', max_results: 500)
		@resources = res['resources']
		render 'demo/resources'
  end
	
	def new 
		render 'demo/new'
	end
	
	def new_upload
		file = params["file"]
		Cloudinary::Uploader.upload(file, :resource_type => :image,
    :public_id => "asdf2",
    :chunk_size => 6_000_000
		)
		render 'demo/index'
	end
  
	def pdfs
		res = Cloudinary::Api.resources(resource: 'image', format: 'pdf', max_results: 500)
		@pdfs = res['resources'].select{|r|r["format"]== 'pdf'}
		render 'demo/pdfs'
	end

  private

  def local_image_path(name)
    Rails.root.join('uploads', name).to_s
  end

end

app/views/demo/_image_box.html.erb
<div class="item">

  <div class="caption">
    Uploaded image
  </div>

  <div class="public_id">
    Image Public ID:
    <%= upload["public_id"] %>
  </div>
  
  <%= image_tag(upload["url"]) %>
  <div class="link">
    <%= link_to(upload["url"], upload["url"], :target => '_blank') %>
  </div>

  <div class="caption">
    <%= description %>
  </div>

  <% options_with_format = options.merge(:format => 'jpg') %>
  <%= cl_image_tag(upload["public_id"], options_with_format) %>
  <div class="link">
    <% link_url = cloudinary_url(upload["public_id"], options_with_format) %>
    <%= link_to(link_url, link_url, :target => '_blank') %>
  </div>

</div>

app/views/demo/configuration_missing.html.erb
<div>
  <h1>
    Missing cloudinary.yml
  </h1>
  <p>
    You will need a Cloudinary account to run this demo project.
    <ol>
      <li>
        If you don't have an account, sign up for free
        <%= link_to 'here', 'https://cloudinary.com/users/register/free' %>.
      </li>
      <li>
        Download your customized cloudinary.yml configuration file using our
        <%= link_to 'Management Console', 'https://cloudinary.com/console' %>
        or by following this
        <%= link_to 'direct link', 'http://cloudinary.com/console/cloudinary.yml' %>.
      </li>
      <li>
        Place cloudinary.yml into the project's config directory.
      </li>
      <li>
        Restart your Rails server process.
      </li>
    </ol>
  </p>
</div>

app/views/demo/index.html.erb
<h1>
  Uploads and Transformations
</h1>

<% @resources.each do |resource| %>
	Name: <%= resource["url"].split('/').last %>
	 URL: <%= resource.secure_url %>
	 
<% end %>

app/views/demo/new.html.erb
<%= form_tag({action: :new_upload, method: :post}, multipart: true) do %>
	<%= file_field_tag 'file' %>
	<%= date_field_tag 'date' %>
	<br>
	<br>
	<%= button_tag 'upload' %>
<% end %>
 

app/views/demo/pdfs.html.erb
<div class='row'>
	<div class='col-lg-12'>
	<% @pdfs.each do |pdf| %>
		<ul>
			<strong><li><%= link_to pdf["secure_url"].split('/').last, pdf["url"] %></li></strong>
			<li>format: <%= pdf["format"] %></li>
			<li>secure_url: <%= pdf["secure_url"] %></li>
		</ul>
		<hr />
		<% end %>
	</div>
</div>
 

app/views/demo/resources.html.erb
<% @resources.each do |res| %>
	<ul>
	<li>public_id: <%= res["public_id"] %></li>
	<li>format: <%= res["format"] %></li>
	<li>created_at: <%= res["created_at"] %></li>
	<li>width: <%= res["width"] %></li>
	<li>height: <%= res["height"] %></li>
	<li>url: <%= link_to 'show_image', res["url"] %></li>
	<li>secure_url: <%= res["secure_url"] %></li>
	<hr />
	</ul>
	<% end %>
<hr />
 

app/views/demo/zoom.html.erb
<% @images.each do |image| %>
	<hr />
	<ul>
		<li>public_id: <%= image["public_id"] %></li>
		<li>format: <%= image["format"] %></li>
		<li>url: <%= image["url"] %></li>
		<li>secure_url: <%= link_to 'show_image', image["secure_url"] %></li>
	</ul>
	<% end %>
<hr />
 

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
			<li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">Resources</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= pdfs_path %>">Pdfs</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= images_path %>">Images</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= new_path %>">New</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
<title>Cloudinary - Basic Rails Sample</title>
<%= stylesheet_link_tag "demo", :media => "all" %>
<%= csrf_meta_tags %>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  </head>
  <body>
 
		<%= render partial: 'layouts/navbar' %>
		<%= yield %>
		
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>